<?php 
	class CrudHojaDeVida{
		public function agregar($datos){
			$obj= new conectar();
			$conexion=$obj->conexion();
    
			$sql="INSERT into hojadevida (fecha,
                                          programa,
                                          primerapellido,
                                          segundoapellido,
                                          nombres,
                                          cedula,
                                          fechaNacimineto,
                                          estadoCivil,
                                          direccion,
                                          telefono,
                                          eps,
                                          correoElectronico,
                                          ciudad,
                                          instituto_01,
                                          titulo_01,
                                          fecha_01,
                                          instituto_02,
                                          titulo_02,
                                          fecha_02,
                                          ingles_01,
                                          ingles_02,
                                          ingles_03,
                                          ingles_04,
                                          aleman_01,
                                          aleman_02,
                                          aleman_03,
                                          aleman_04,
                                          frances_01,
                                          frances_02,
                                          frances_03,
                                          frances_04,
                                          otros_01,
                                          otros_02,
                                          otros_03,
                                          otros_04,
                                          apartado_03,
                                          apartado_04,
                                          apartado_05,
                                          apartado_06,
                                          entidad_01,
                                          cargo_01,
                                          funcion_01,
                                          duracion_01,
                                          entidad_02,
                                          cargo_02,
                                          funcion_02,
                                          duracion_02,
                                          apartado_08,
                                          idUsuario)
									values ('$datos[0]',
											'$datos[1]',
                                            '$datos[2]',
                                            '$datos[3]',
                                            '$datos[4]',
                                            '$datos[5]',
											'$datos[6]',
                                            '$datos[7]',
                                            '$datos[8]',
                                            '$datos[9]',
                                            '$datos[10]',
                                            '$datos[11]',
                                            '$datos[12]',
                                            '$datos[13]',
											'$datos[14]',
                                            '$datos[15]',
                                            '$datos[16]',
                                            '$datos[17]',                                       
											'$datos[18]',
                                            '$datos[19]',
                                            '$datos[20]',
                                            '$datos[21]',                                       
											'$datos[22]',
                                            '$datos[23]',
                                            '$datos[24]',
                                            '$datos[25]',                                       
											'$datos[26]',
                                            '$datos[27]',
                                            '$datos[28]',
                                            '$datos[29]',                                       
											'$datos[30]',
                                            '$datos[31]',
                                            '$datos[32]',
                                            '$datos[33]', 
                                            '$datos[34]', 
                                            '$datos[35]', 
                                            '$datos[36]',
                                            '$datos[37]', 
                                            '$datos[38]',
                                            '$datos[39]',
                                            '$datos[40]',
                                            '$datos[41]', 
                                            '$datos[42]', 
                                            '$datos[43]', 
                                            '$datos[44]',
                                            '$datos[45]', 
                                            '$datos[46]', 
                                            '$datos[47]', 
                                            '$datos[48]')";
			return mysqli_query($conexion,$sql);
        }
        public function obtenDatos($cedulaU){
			$obj= new conectar();
			$conexion=$obj->conexion();

			$sql="SELECT  fecha,
                          programa,
                          primerapellido,
                          segundoapellido,
                          nombres,
                          cedula,
                          fechaNacimineto,
                          estadoCivil,
                          direccion,
                          telefono,
                          eps,
                          correoElectronico,
                          ciudad,
                          instituto_01,
                          titulo_01,
                          fecha_01,
                          instituto_02,
                          titulo_02,
                          fecha_02,
                          ingles_01,
                          ingles_02,
                          ingles_03,
                          ingles_04,
                          aleman_01,
                          aleman_02,
                          aleman_03,
                          aleman_04,
                          frances_01,
                          frances_02,
                          frances_03,
                          frances_04,
                          otros_01,
                          otros_02,
                          otros_03,
                          otros_04,
                          apartado_03,
                          apartado_04,
                          apartado_05,
                          apartado_06,
                          entidad_01,
                          cargo_01,
                          funcion_01,
                          duracion_01,
                          entidad_02,
                          cargo_02,
                          funcion_02,
                          duracion_02,
                          apartado_08
                          
					from hojadevida 
					where cedula='$cedulaU'";
		
			$result=mysqli_query($conexion,$sql);
			$ver=mysqli_fetch_row($result);

			$datos=array(
                'fecha' => $ver[0],
                'programa'=> $ver[1],
                'primerapellido'=> $ver[2],
                'segundoapellido'=> $ver[3],
                'nombres'=> $ver[4],
                'cedula'=> $ver[5],
                'fechaNacimineto'=> $ver[6],
                'estadoCivil'=> $ver[7],
                'direccion'=> $ver[8],
                'telefono'=> $ver[9],
                'eps'=> $ver[10],
                'correoElectronico'=> $ver[11],
                'ciudad'=> $ver[12],
                'instituto_01'=> $ver[13],
                'titulo_01'=> $ver[14],
                'fecha_01' => $ver[15],
                'instituto_02'=> $ver[16],
                'titulo_02'=> $ver[17],
                'fecha_02'=> $ver[18],
                'ingles_01'=> $ver[19],
                'ingles_02'=> $ver[20],
                'ingles_03'=> $ver[21],
                'ingles_04'=> $ver[22],
                'aleman_01'=> $ver[23],
                'aleman_02'=> $ver[24],
                'aleman_03'=> $ver[25],
                'aleman_04'=> $ver[26],
                'frances_01'=> $ver[27],
                'frances_02'=> $ver[28],
                'frances_03'=> $ver[29],
                'frances_04'=> $ver[30],
                'otros_01'=> $ver[31],
                'otros_02'=> $ver[32],
                'otros_03'=> $ver[33],
                'otros_04'=> $ver[34],
                'apartado_03'=> $ver[35],
                'apartado_04'=> $ver[36],
                'apartado_05'=> $ver[37],
                'apartado_06'=> $ver[38],
                'entidad_01'=> $ver[39],
                'cargo_01'=> $ver[40],
                'funcion_01'=> $ver[41],
                'duracion_01'=> $ver[42],
                'entidad_02'=> $ver[43],
                'cargo_02'=> $ver[44],
                'funcion_02'=> $ver[45],
                'duracion_02' => $ver[46],
                'apartado_08'=> $ver[47]
				);
			return $datos;
        }
        
        public function obtenDatosX($cedulaX){
			$obj= new conectar();
			$conexion=$obj->conexion();

			$sql="SELECT  fecha,
                          programa,
                          primerapellido,
                          segundoapellido,
                          nombres,
                          cedula,
                          fechaNacimineto,
                          estadoCivil,
                          direccion,
                          telefono,
                          eps,
                          correoElectronico,
                          ciudad,
                          instituto_01,
                          titulo_01,
                          fecha_01,
                          instituto_02,
                          titulo_02,
                          fecha_02,
                          ingles_01,
                          ingles_02,
                          ingles_03,
                          ingles_04,
                          aleman_01,
                          aleman_02,
                          aleman_03,
                          aleman_04,
                          frances_01,
                          frances_02,
                          frances_03,
                          frances_04,
                          otros_01,
                          otros_02,
                          otros_03,
                          otros_04,
                          apartado_03,
                          apartado_04,
                          apartado_05,
                          apartado_06,
                          entidad_01,
                          cargo_01,
                          funcion_01,
                          duracion_01,
                          entidad_02,
                          cargo_02,
                          funcion_02,
                          duracion_02,
                          apartado_08
					from hojadevida 
					where cedula='$cedulaX'";
		
			$result=mysqli_query($conexion,$sql);
			$ver=mysqli_fetch_row($result);

			$datos=array(
                'fecha' => $ver[0],
                'programa'=> $ver[1],
                'primerapellido'=> $ver[2],
                'segundoapellido'=> $ver[3],
                'nombres'=> $ver[4],
                'cedula'=> $ver[5],
                'fechaNacimineto'=> $ver[6],
                'estadoCivil'=> $ver[7],
                'direccion'=> $ver[8],
                'telefono'=> $ver[9],
                'eps'=> $ver[10],
                'correoElectronico'=> $ver[11],
                'ciudad'=> $ver[12],
                'instituto_01'=> $ver[13],
                'titulo_01'=> $ver[14],
                'fecha_01' => $ver[15],
                'instituto_02'=> $ver[16],
                'titulo_02'=> $ver[17],
                'fecha_02'=> $ver[18],
                'ingles_01'=> $ver[19],
                'ingles_02'=> $ver[20],
                'ingles_03'=> $ver[21],
                'ingles_04'=> $ver[22],
                'aleman_01'=> $ver[23],
                'aleman_02'=> $ver[24],
                'aleman_03'=> $ver[25],
                'aleman_04'=> $ver[26],
                'frances_01'=> $ver[27],
                'frances_02'=> $ver[28],
                'frances_03'=> $ver[29],
                'frances_04'=> $ver[30],
                'otros_01'=> $ver[31],
                'otros_02'=> $ver[32],
                'otros_03'=> $ver[33],
                'otros_04'=> $ver[34],
                'apartado_03'=> $ver[35],
                'apartado_04'=> $ver[36],
                'apartado_05'=> $ver[37],
                'apartado_06'=> $ver[38],
                'entidad_01'=> $ver[39],
                'cargo_01'=> $ver[40],
                'funcion_01'=> $ver[41],
                'duracion_01'=> $ver[42],
                'entidad_02'=> $ver[43],
                'cargo_02'=> $ver[44],
                'funcion_02'=> $ver[45],
                'duracion_02' => $ver[46],
                'apartado_08'=> $ver[47]
				);
			return $datos;
        }
        
        public function actualizar($datos){
			$obj= new conectar();
			$conexion=$obj->conexion();

			$sql="UPDATE hojadevida set programa='$datos[0]',
			                            primerapellido='$datos[1]',
									    segundoapellido='$datos[2]',
                                        nombres='$datos[3]',
                                        fechaNacimineto='$datos[4]',
                                        estadoCivil='$datos[5]',
                                        direccion='$datos[6]',
                                        telefono='$datos[7]',
                                        eps='$datos[8]',
                                        correoElectronico='$datos[9]',
									    ciudad='$datos[10]',
                                        instituto_01='$datos[11]',
                                        titulo_01='$datos[12]',
                                        fecha_01='$datos[13]',
                                        instituto_02='$datos[14]',
                                        titulo_02='$datos[15]',
                                        fecha_02='$datos[16]',
                                        ingles_01='$datos[17]',
									    ingles_02='$datos[18]',
                                        ingles_03='$datos[19]',
                                        ingles_04='$datos[20]',
                                        aleman_01='$datos[21]',
                                        aleman_02='$datos[22]',
                                        aleman_03='$datos[23]',
                                        aleman_04='$datos[24]',
                                        frances_01='$datos[25]',
									    frances_02='$datos[26]',
                                        frances_03='$datos[27]',
                                        frances_04='$datos[28]',
                                        otros_01='$datos[29]',
                                        otros_02='$datos[30]',
                                        otros_03='$datos[31]',
                                        otros_04='$datos[32]',
                                        apartado_03='$datos[33]',
                                        apartado_04='$datos[34]',
                                        apartado_05='$datos[35]',
                                        apartado_06='$datos[36]',
                                        entidad_01='$datos[37]',
                                        cargo_01='$datos[38]',
                                        funcion_01='$datos[39]',
                                        duracion_01='$datos[40]',
                                        entidad_02='$datos[41]',
                                        cargo_02='$datos[42]',
                                        funcion_02='$datos[43]',
                                        duracion_02='$datos[44]',
                                        apartado_08='$datos[45]'
						                where cedula='$datos[46]'";
			
			return mysqli_query($conexion,$sql);
		}
	
        public function eliminar($cedula){
            $obj= new conectar();
			$conexion=$obj->conexion();
			$sql="DELETE from hojadevida where cedula='$cedula'";
			return mysqli_query($conexion,$sql);
        }
        

    }
    
 ?>